### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by weiweihuanghuang** [BelaFrank/StringSmash#4]
Since Version 2.6.1 (1220) on Glyphs App this doesn't work, when I try to "Get" the left and right list, and have no seperator, then save string:

I get this error

```
Traceback (most recent call last):

  File "/Library/Python/2.7/site-packages/vanilla-0.1-py2.7.egg/vanilla/vanillaBase.py", line 218, in action_
    self.callback(sender)

  File "StringSmash.py", line 241, in button_saveString
    theString = self.generateString(self.delimL, self.delimR, self.listL, self.listR, self.flip, self.trio, False)

  File "StringSmash.py", line 372, in generateString
    return self.makePairString(listL, listR, delimL, delimR)

  File "StringSmash.py", line 302, in makePairString
    pairList = [aString + '/' + a + '/' + b + bString for b in bList for a in aList]

TypeError: cannot concatenate 'str' and 'NoneType' objects
```

@schriftgestalt What changed in the API, it worked just one (?) version ago.

**Comment by weiweihuanghuang** [comment]
Oh wait I see it's because the new line glyph is handled differently now...
